language: ruby
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0

before_install:
  - gem install ruby-debug-ide
  - nvm install 8.11.3
  - echo "8.11.3" > .nvmrc

before_script:
  - nvm use
  - npm install -g typescript -v 2.1.5
  - npm install
  - cd client && npm install && cd ..
  - cd server && npm install && cd ..
  - npm run compile
script: nvm use && npm run test && npm run test-debugger
