version: '{build}'
image: Visual Studio 2015
branches:
  only:
    - master
clone_depth: 10
install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install ruby-debug-ide -N
  - ps: Install-Product node lts
  - yarn --cache-folder=.yarn-cache --no-progress --pure-lockfile
  - git clone https://github.com/emscripten-core/emsdk.git
  - cd emsdk
  - emsdk install latest --vs2015
  - emsdk activate latest
build_script:
  - emsdk_env.bat
  - yarn run lerna run build --scope vscode-ruby-debugger
test_script:
  - yarn test

cache:
  - .yarn-cache

environment:
  matrix:
    - ruby_version: '24-x64'
    - ruby_version: '25-x64'
    - ruby_version: '26-x64'
