version: '{build}'
image: Windows Server 2019
branches:
  only:
    - master
clone_depth: 10
install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - ridk install 1 2 3
  - gem install ruby-debug-ide
  - ps: Install-Product node lts
  - yarn install
build_script:
  - ps: Switch-DockerLinux
  - yarn build
test_script:
  - yarn test

environment:
  matrix:
    - ruby_version: '24'
    - ruby_version: '24-x64'
    - ruby_version: '25'
    - ruby_version: '25-x64'
    - ruby_version: '26'
    - ruby_version: '26-x64'
